# Generated by Django 5.1.15 on 2026-03-21 20:33

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_bot', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_room_code, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for players'), ('SUBMITTING', 'Submitting statements'), ('GUESSING', 'Guessing'), ('RESULTS', 'Results')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truth_guess_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_guess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_identifications', to='game.player')),
                ('target_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses_received', to='game.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses_made', to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_truth', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='game.player')),
            ],
        ),
    ]
